INSERT INTO SCORE (USER_ID, SCORE, SCORE_DATE_TIME) VALUES
(3, 3, CURRENT_TIMESTAMP),
(4, 3, CURRENT_TIMESTAMP),
(5, 3, CURRENT_TIMESTAMP),
(6, 3, CURRENT_TIMESTAMP),
(7, 8, CURRENT_TIMESTAMP),
(8, 5, CURRENT_TIMESTAMP),
(9, 7, CURRENT_TIMESTAMP),
(10, 1, CURRENT_TIMESTAMP),
(11, 4, CURRENT_TIMESTAMP),
(12, 9, CURRENT_TIMESTAMP),
(13, 6, CURRENT_TIMESTAMP),
(14, 2, CURRENT_TIMESTAMP),
(15, 8, CURRENT_TIMESTAMP),
(16, 5, CURRENT_TIMESTAMP),
(17, 7, CURRENT_TIMESTAMP),
(18, 3, CURRENT_TIMESTAMP),
(19, 6, CURRENT_TIMESTAMP),
(20, 1, CURRENT_TIMESTAMP),
(21, 4, CURRENT_TIMESTAMP),
(22, 9, CURRENT_TIMESTAMP),
(23, 6, CURRENT_TIMESTAMP),
(24, 8, CURRENT_TIMESTAMP),
(25, 5, CURRENT_TIMESTAMP);
INSERT INTO USERS (NAME, EMAIL) VALUES
('name1', 'email2@gmail.com'),
('name2', 'email2@gmail.com'),
('name3', 'email3@gmail.com'),
('name4', 'email4@gmail.com'),
('name5', 'email5@gmail.com'),
('name6', 'email6@gmail.com'),
('name7', 'email7@gmail.com'),
('name8', 'email8@gmail.com'),
('name9', 'email9@gmail.com'),
('name10', 'email10@gmail.com'),
('name11', 'email11@gmail.com'),
('name11', 'email12@gmail.com'),
('name12', 'email13@gmail.com'),
('name13', 'email14@gmail.com'),
('name14', 'email15@gmail.com'),
('name15', 'email16@gmail.com'),
('name16', 'email17@gmail.com'),
('name17', 'email18@gmail.com'),
('name18', 'email19@gmail.com'),
('name19', 'email20@gmail.com'),
('name20', 'email21@gmail.com');


