DROP TABLE IF EXISTS SCORE;
CREATE TABLE SCORE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    SCORE INT CHECK (SCORE >= 0 AND SCORE <= 10),
    SCORE_DATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS (
    USER_ID INT AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL,
    NAME VARCHAR(255)
);
